name: ai-video-transcribe
region: ams3

services:
  # Web service - serves the Next.js frontend and API routes
  - name: web
    source:
      image:
        registry_type: DOCKER_HUB
        repository: ai-video-transcribe
        tag: web-latest
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    health_check:
      http_path: /
    routes:
      - path: /
    envs:
      # App Configuration
      - key: NEXT_PUBLIC_APP_URL
        scope: RUN_TIME
        type: SECRET
      - key: NEXT_PUBLIC_MAX_FILE_SIZE
        value: "104857600"
        scope: RUN_TIME
      
      # Database
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      
      # Redis/Queue Configuration
      - key: REDIS_HOST
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_PORT
        value: "6379"
        scope: RUN_TIME
      - key: REDIS_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_URL
        scope: RUN_TIME
        type: SECRET
      - key: ENABLE_QUEUE_WORKERS
        value: "false"
        scope: RUN_TIME
      - key: TRANSCRIPTION_CONCURRENCY
        value: "2"
        scope: RUN_TIME
      - key: CONTENT_IDEAS_CONCURRENCY
        value: "1"
        scope: RUN_TIME
      
      # Authentication
      - key: GOOGLE_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: GOOGLE_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: AUTH_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: NEXTAUTH_URL
        scope: RUN_TIME
        type: SECRET
      
      # OpenAI/AI Configuration
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: OPENAI_MODEL_NAME
        value: "gpt-4"
        scope: RUN_TIME
      - key: GROQ_API_KEY
        scope: RUN_TIME
        type: SECRET
      
      # Stripe Configuration
      - key: STRIPE_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
        scope: RUN_TIME
        type: SECRET
      - key: STRIPE_WEBHOOK_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: NEXT_PUBLIC_STRIPE_PRICE_ID_STARTER
        scope: RUN_TIME
        type: SECRET
      - key: NEXT_PUBLIC_STRIPE_PRICE_ID_PRO
        scope: RUN_TIME
        type: SECRET
      
      # S3 Configuration
      - key: S3_ENDPOINT_URL
        scope: RUN_TIME
        type: SECRET
      - key: S3_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
      - key: S3_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: S3_BUCKET_NAME
        scope: RUN_TIME
        type: SECRET
      - key: S3_REGION
        value: "us-east-1"
        scope: RUN_TIME
      
      # Credits System
      - key: CREDITS_FREE
        value: "100"
        scope: RUN_TIME
      - key: CREDITS_STARTER
        value: "1000"
        scope: RUN_TIME
      - key: CREDITS_PRO
        value: "5000"
        scope: RUN_TIME
      - key: FREE_TIER_INITIAL_CREDITS
        value: "100"
        scope: RUN_TIME
      - key: FREE_TIER_REFRESH_CREDITS
        value: "50"
        scope: RUN_TIME
      - key: FREE_TIER_REFRESH_INTERVAL_DAYS
        value: "30"
        scope: RUN_TIME
      - key: FREE_TIER_MAX_CREDITS
        value: "200"
        scope: RUN_TIME
      - key: STARTER_TIER_MONTHLY_CREDITS
        value: "1000"
        scope: RUN_TIME
      - key: PRO_TIER_MONTHLY_CREDITS
        value: "5000"
        scope: RUN_TIME
      
      # Credit Costs
      - key: CREDITS_CAPTION_FIRST_FIXED
        value: "10"
        scope: RUN_TIME
      - key: CREDITS_PER_10_MIN_STANDARD
        value: "5"
        scope: RUN_TIME
      - key: CREDITS_PER_10_MIN_PREMIUM
        value: "10"
        scope: RUN_TIME
      - key: CREDITS_BASIC_SUMMARY_FIXED
        value: "15"
        scope: RUN_TIME
      - key: CREDITS_EXTENDED_SUMMARY_FIXED
        value: "25"
        scope: RUN_TIME
      
      # Content Ideas Credit Costs
      - key: CONTENT_IDEA_NORMAL_CREDIT_COST
        value: "20"
        scope: RUN_TIME
      - key: CONTENT_IDEA_COMMENT_SMALL_CREDIT_COST
        value: "25"
        scope: RUN_TIME
      - key: CONTENT_IDEA_COMMENT_MEDIUM_CREDIT_COST
        value: "35"
        scope: RUN_TIME
      - key: CONTENT_IDEA_COMMENT_LARGE_CREDIT_COST
        value: "50"
        scope: RUN_TIME
      - key: CONTENT_IDEA_COMMENT_XLARGE_CREDIT_COST
        value: "75"
        scope: RUN_TIME
      
      # YouTube Configuration
      - key: MAX_YOUTUBE_COMMENTS_TO_FETCH
        value: "500"
        scope: RUN_TIME
      - key: MIN_YOUTUBE_COMMENTS_FOR_ANALYSIS
        value: "10"
        scope: RUN_TIME
      
      # Local/Cron
      - key: LOCAL_CRON_SCRIPT_SECRET
        scope: RUN_TIME
        type: SECRET

  # Worker service - runs background job processing
  - name: worker
    source:
      image:
        registry_type: DOCKER_HUB
        repository: ai-video-transcribe
        tag: worker-latest
    instance_count: 1
    instance_size_slug: basic-xs
    envs:
      # Database
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      
      # Redis/Queue Configuration
      - key: REDIS_HOST
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_PORT
        value: "6379"
        scope: RUN_TIME
      - key: REDIS_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_URL
        scope: RUN_TIME
        type: SECRET
      - key: ENABLE_QUEUE_WORKERS
        value: "true"
        scope: RUN_TIME
      - key: TRANSCRIPTION_CONCURRENCY
        value: "2"
        scope: RUN_TIME
      - key: CONTENT_IDEAS_CONCURRENCY
        value: "1"
        scope: RUN_TIME
      
      # OpenAI/AI Configuration
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: OPENAI_MODEL_NAME
        value: "gpt-4"
        scope: RUN_TIME
      - key: GROQ_API_KEY
        scope: RUN_TIME
        type: SECRET
      
      # S3 Configuration
      - key: S3_ENDPOINT_URL
        scope: RUN_TIME
        type: SECRET
      - key: S3_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
      - key: S3_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: S3_BUCKET_NAME
        scope: RUN_TIME
        type: SECRET
      - key: S3_REGION
        value: "us-east-1"
        scope: RUN_TIME
      
      # YouTube Configuration
      - key: MAX_YOUTUBE_COMMENTS_TO_FETCH
        value: "500"
        scope: RUN_TIME
      - key: MIN_YOUTUBE_COMMENTS_FOR_ANALYSIS
        value: "10"
        scope: RUN_TIME
      
      # Credit Costs (needed for job processing)
      - key: CREDITS_CAPTION_FIRST_FIXED
        value: "10"
        scope: RUN_TIME
      - key: CREDITS_PER_10_MIN_STANDARD
        value: "5"
        scope: RUN_TIME
      - key: CREDITS_PER_10_MIN_PREMIUM
        value: "10"
        scope: RUN_TIME
      - key: CREDITS_BASIC_SUMMARY_FIXED
        value: "15"
        scope: RUN_TIME
      - key: CREDITS_EXTENDED_SUMMARY_FIXED
        value: "25"
        scope: RUN_TIME
      - key: CONTENT_IDEA_NORMAL_CREDIT_COST
        value: "20"
        scope: RUN_TIME
      - key: CONTENT_IDEA_COMMENT_SMALL_CREDIT_COST
        value: "25"
        scope: RUN_TIME
      - key: CONTENT_IDEA_COMMENT_MEDIUM_CREDIT_COST
        value: "35"
        scope: RUN_TIME
      - key: CONTENT_IDEA_COMMENT_LARGE_CREDIT_COST
        value: "50"
        scope: RUN_TIME
      - key: CONTENT_IDEA_COMMENT_XLARGE_CREDIT_COST
        value: "75"
        scope: RUN_TIME 